name: Build Unity Project

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        targetPlatform: [StandaloneWindows64, StandaloneOSX]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 6000.0.34f1
          license: ${{ secrets.UNITY_LICENSE }}

      - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}