name: Unity Build Workflow 😎

on: [push, pull_request]

jobs:
  build:
    name: Build Unity Project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Obsługa plików w Git LFS (Large File Storage)

      # Cache Unity Library (przyspiesza buildy)
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library  # Folder z cache Unity
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build project
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}  # Klucz licencyjny Unity
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}    # E-mail Unity
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}  # Hasło do konta Unity
        with:
          targetPlatform: StandaloneWindows64  # Platforma docelowa: Windows 64-bit
          allowDirtyBuild: true  # Zezwala na budowanie z lokalnymi zmianami bez czyszczenia

      # Upload built artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build  # Nazwa artefaktu
          path: build  # Ścieżka do folderu z wygenerowanym buildem Unity

      # Return Unity license (zawsze zwraca licencję)
      - name: Return Unity license
        uses: game-ci/unity-return-license@v2
        if: always()  # Wykonuje się nawet, jeśli wcześniejsze kroki zawiodą