name: Build and Test Unity Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Windows Player
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Unity
      - name: Set up Unity
        uses: game-ci/unity-action@v2
        with:
          version: '2020.3.11f1' # Wersja Unity, którą używasz

      # Build project for Windows
      - name: Build for Windows
        run: |
          unity -batchmode -quit -projectPath . -buildWindows64Player "build/Windows/MyGame.exe"

      # Upload build for testing
      - name: Upload Build for Testing
        uses: actions/upload-artifact@v2
        with:
          name: Windows-Build
          path: build/Windows/MyGame.exe