name: Build Unity Project for Windows and macOS

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'

jobs:
  buildWithWindows:
    name: Build for StandaloneWindows and StandaloneWindows64
    runs-on: windows-latest  
    outputs:
      buildVersion: ${{ steps.buildStep.outputs.buildVersion }}
    strategy:
      matrix:
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Unity Project
        id: buildStep
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2022.3.10f1  # Określamy wersję Unity
          buildMethod: Cgs.Editor.BuildCgs.BuildOptions
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: cgs-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  buildWithMac:
    name: Build for StandaloneOSX
    runs-on: macos-latest
    needs: [buildWithWindows]
    outputs:
      buildVersion: ${{ steps.buildStep.outputs.buildVersion }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Unity Project
        id: buildStep
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneOSX
          unityVersion: 2022.3.10f1  # Określamy wersję Unity
          buildMethod: Cgs.Editor.BuildCgs.BuildOptions
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: cgs-StandaloneOSX
          path: build/StandaloneOSX